name: lte_env
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - basemap=1.3.2
  - basemap-data=1.3.2
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=6.0.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2023.11.17
  - cffi=1.15.1
  - cftime=1.5.1.1
  - charset-normalizer=2.1.1
  - comm=0.1.2
  - contourpy=1.0.2
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - cython=0.29.32
  - dbus=1.13.18
  - dcor=0.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.12.1
  - future=0.18.3
  - geos=3.8.0
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gpytorch=1.8.1
  - graphite2=1.3.13
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - intel-openmp=2021.4.0
  - ipykernel=6.20.2
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - jack=1.9.21
  - jbig=2.1
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=7.3.5
  - jupyter_core=4.11.2
  - jupyter_server=1.16.0
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.6
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=2.2.1
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.3.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpg123=1.31.2
  - mpi=1.0
  - mpich=4.1.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.3.7
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - networkx=2.8.4
  - ninja=1.11.0
  - notebook=6.4.12
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.82
  - numexpr=2.7.3
  - openssl=3.1.4
  - packaging=23.0
  - pandas=1.4.4
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - proj=7.2.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyrsistent=0.18.1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytorch=1.10.2
  - pytz=2022.7.1
  - pyzmq=23.0.0
  - qt-main=5.15.6
  - readline=8.1.2
  - requests=2.28.2
  - scikit-learn=1.1.3
  - scipy=1.8.0
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - send2trash=1.8.0
  - setuptools=65.5.0
  - shapely=1.8.4
  - sip=6.5.1
  - six=1.15.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.6.2
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=14.0.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.0
  - wheel=0.38.4
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.12.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - llvmlite==0.38.1
    - mpi4py==3.1.5
    - netcdftime==1.0.0a2
    - nipals==0.5.5
    - numba==0.55.1
    - numpy==1.23.4
    - pyproj==3.4.0
    - scienceplots==2.1.1
